# Generated by Django 5.2.5 on 2025-10-31 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("date", "date"), ("place", "place"), ("custom", "custom")],
                        max_length=10,
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("multiple", models.BooleanField(default=False)),
                ("allow_change_vote", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=200, null=True)),
                ("date_value", models.DateField(blank=True, null=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["event", "is_closed"], name="idx_poll_event_closed"),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["end_at"], name="idx_poll_end_at"),
        ),
        migrations.AddIndex(
            model_name="polloption",
            index=models.Index(fields=["poll"], name="idx_polloption_poll"),
        ),
        migrations.AddConstraint(
            model_name="polloption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_value__isnull", False)),
                fields=("poll", "date_value"),
                name="uq_polloption_poll_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="polloption",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("label__isnull", False), models.Q(("label", ""), _negated=True)
                ),
                fields=("poll", "label"),
                name="uq_polloption_poll_label",
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["poll"], name="idx_vote_poll"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["option"], name="idx_vote_option"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["user"], name="idx_vote_user"),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("poll", "user", "option"), name="uq_vote_poll_user_option"
            ),
        ),
    ]
