# Generated by Django 5.2.5 on 2025-10-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
