# Generated by Django 5.2.5 on 2025-11-03 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_invite"),
        ("polls", "0002_poll_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="closing_notification_for_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="closing_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["closing_notification_sent_at"],
                name="idx_poll_closing_notified",
            ),
        ),
    ]
