[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["apps", "config"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
extend-exclude = ["venv", "migrations"]
per-file-ignores = {"config/settings.py" = "E501"}

[tool.mypy]
python_version = "3.11"
plugins = ["mypy_django_plugin.main"]
strict = true
ignore_missing_imports = true
exclude = ["venv", "migrations"]

[tool.django-stubs]
django_settings_module = "config.settings"
