# Generated by Django 5.2.5 on 2025-10-26 15:20

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profile_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.models.user_avatar_upload_to,
                verbose_name="Аватар",
            ),
        ),
    ]
