# Generated by Django 5.2.5 on 2025-11-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_email_notifications_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="user",
            name="timezone",
        ),
        migrations.AlterField(
            model_name="user",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Получайте напоминания и обновления о событиях на электронную почту.",
                verbose_name="Уведомления на email включены",
            ),
        ),
    ]
