# Generated by Django 5.2.5 on 2025-10-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("category", models.CharField(blank=True, max_length=50, verbose_name="Категория")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="Старт")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="Финиш")),
                ("location", models.CharField(blank=True, max_length=200, verbose_name="Локация")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ("-start_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("organizer", "Организатор"), ("member", "Участник")],
                        default="member",
                        max_length=16,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата присоединения"),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
            },
        ),
    ]
