# Generated by Django 5.2.5 on 2025-10-26 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="events.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["owner", "start_at"], name="idx_event_owner_start"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_at"], name="idx_event_start"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["event"], name="idx_participant_event"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["user", "event"], name="idx_participant_user_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="uq_participant_user_event"
            ),
        ),
    ]
