# Generated by Django 5.2.5 on 2025-10-28 11:34

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(
                        default=apps.events.models._generate_invite_token,
                        help_text="Уникальный токен приглашения.",
                        max_length=128,
                        unique=True,
                        verbose_name="Токен",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает в")),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, verbose_name="Максимум использований"),
                ),
                (
                    "uses_count",
                    models.PositiveIntegerField(default=0, verbose_name="Количество использований"),
                ),
                ("is_revoked", models.BooleanField(default=False, verbose_name="Отозвано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвайт",
                "verbose_name_plural": "Инвайты",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event", "expires_at", "is_revoked"], name="inv_event_exp_rev_idx"
                    )
                ],
            },
        ),
    ]
