# Generated by Django 5.2.5 on 2025-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[("organizer", "Организатор"), ("member", "Участник")],
                db_index=True,
                default="member",
                max_length=16,
                verbose_name="Роль",
            ),
        ),
    ]
