# Generated by Django 5.2.5 on 2025-11-05 13:14

from django.db import migrations, models


TITLE_LIMIT = 16


def truncate_event_titles(apps, _schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.only("id", "title"):
        title = event.title or ""
        trimmed = title[:TITLE_LIMIT]
        if title != trimmed:
            Event.objects.filter(pk=event.pk).update(title=trimmed)


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_participant_role"),
    ]

    operations = [
        migrations.RunPython(truncate_event_titles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=16, verbose_name="Название"),
        ),
    ]
