# Generated by Django 5.2.5 on 2025-10-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_lists",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список задач",
                "verbose_name_plural": "Списки задач",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Нужно сделать"),
                            ("doing", "В работе"),
                            ("done", "Готово"),
                        ],
                        default="todo",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="Начать")),
                ("due_at", models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="events.participant",
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependents",
                        to="tasks.task",
                        verbose_name="Зависимости",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.tasklist",
                        verbose_name="Список задач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="tasklist",
            index=models.Index(fields=["event", "order"], name="idx_tasklist_event_order"),
        ),
        migrations.AddIndex(
            model_name="tasklist",
            index=models.Index(fields=["event", "id"], name="idx_tasklist_event_id"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["list", "order"], name="idx_task_list_order"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["list", "status"], name="idx_task_list_status"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["list", "id"], name="idx_task_list_id"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["id"], name="idx_task_id"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["list", "due_at"], name="idx_task_list_due"),
        ),
    ]
